config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :categories

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
    resources :collaborations
  end

    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end

    root "homes#home"

    get "/about" => "homes#about"

    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :edit, Post do |post|
      post.collaborating_users.include?(user)
    end

    can :manage, Post do |post|
      post.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user || comment.post.user == user
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts, dependent: :nullify
	validates :title, presence: {message: "Title required!"}

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post, uniqueness: {scope: :user_id}
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :post
	validates :body, 	presence: true,
										uniqueness: {scope: :body}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
    validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ActiveRecord::Base

	mount_uploader :image, ImageUploader

	belongs_to :category
	belongs_to :user

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user
	has_many :votes, dependent: :destroy
	has_many :voting_users, through: :votes, source: :user

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings

	has_many :favourites, dependent: :destroy
	has_many :favouriting_users, through: :favourites, source: :user

	has_many :collaborations, dependent: :destroy
	has_many :collaborating_users, through: :collaborations, source: :user

	validates :title, presence: {message: "Post must have a title!"}, uniqueness: true

	validates :body, presence: {message: "Post must have a body!"}

	scope :recent_three, lambda { order("updated_at DESC").limit(3) }


	def liked_by?(user)
		likes.where(user: user).present?
	end

	def like_for(user)
		likes.find_by_user_id(user)
	end

	def favourited_by?(user)
		favourites.where(user: user).present?
	end

	def favourite_for(user)
		favourites.find_by_user_id(user)
	end

	def vote_for(user)
    votes.find_by_user_id(user)
  end

	def vote_result
   count = 0
   votes.each {|v| v.is_up? ? count += 1 : count -= 1 }
   count
 end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :posts, through: :taggings
  has_many :taggings, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag

  validates :tag_id, uniqueness: {scope: :post_id}
end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :avatar, ImageUploader

	has_secure_password

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :liked_posts, through: :likes, source: :post
	has_many :votes, dependent: :destroy
	has_many :voted_posts, through: :votes, source: :post
	has_many :collaborations, dependent: :destroy
	has_many :collaborated_posts, through: :collaborations, source: :post

	has_many :taggings, dependent: :destroy
	has_many :tagged_posts, through: :taggings, source: :post

	has_many :favourites, dependent: :destroy
	has_many :favourited_posts, through: :favourites, source: :post

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true,
						format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	def full_name
		"#{first_name} #{last_name}".strip.squeeze(" ")
	end

	def recent_five_made
		posts.order("updated_at DESC").limit(5)
	end

	def recent_five_joins
		collaborated_posts.order("created_at DESC").limit(5)
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@post 					= Post.find params[:post_id]
		comment_params 	= params.require(:comment).permit(:body)
		@comment 				= Comment.new(comment_params)
		@comment.post 	= @post
		@comment.user 	= current_user
		respond_to do |format|
			if @comment.save
				CommentsMailer.delay.notify_post_owner(@comment)
				format.html { redirect_to post_path(@post), notice: 	"Comment created!" }
				format.js
			else
				format.html { render "/posts/show" }
				format.js { render :create_failure }
			end
		end
	end

	def destroy
		@post = Post.find params[:post_id]
		@comment = Comment.find params[:id]
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to post_path(@post), notice: "Comment deleted." }
			format.js { render :destroy }
		end
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
			sdf
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
	<div id ="<%= dom_id(comment) %>">
		<div class="row comment-post">
			<div class="col-md-3">
				<% if comment.user.avatar.present? %>
					<%= image_tag comment.user.avatar.url(:square_thumb), :class => "img-circle" %>
				<% else %>
					<%= image_tag ("tree.png"), :class => "avatar" %>
				<% end %>
					<div class="breaker"></div>
				<%= comment.user.full_name %>
			</div>
			<div class="col-md-9">
				<div id="comment-post">
					<p><%= comment.body %></p>
					Posted on: <%= formatted_date(comment.created_at) %>
						<div class="breaker"></div>

						<% if can?(:delete, comment) %>
							<div id="deletion">
								<%= link_to ">> Delete Comment", post_comment_path(@post, comment), method: :delete, data: {confirm: "Are you sure?"} %>
							</div>
						<% end %>
						<div class="breaker"></div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
	<ul>
		<% @comment.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

<%= simple_form_for [@post, @comment], :remote => true do |f| %>
	<%= f.text_area :body, :size => "50x8" %>
	<div class="breaker"></div>
		<%= f.submit 'Comment!', :class => "submit-button" %>
<% end %>

app/views/comments/create.js.erb
$("#comments").prepend("<%= j render 'comment', comment: @comment %>");

<% @comment = Comment.new %>
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/create_failure.js.erb
$("#new_comment").replaceWith("<%= j render 'form'  %>");

app/views/comments/destroy.js.erb
$("#<% dom_id(@comment) %>").fadeOut();