config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :categories

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
    resources :collaborations
  end

    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end

    root "homes#home"

    get "/about" => "homes#about"

    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :edit, Post do |post|
      post.collaborating_users.include?(user)
    end

    can :manage, Post do |post|
      post.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user || comment.post.user == user
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts, dependent: :nullify
	validates :title, presence: {message: "Title required!"}

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post, uniqueness: {scope: :user_id}
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :post
	validates :body, 	presence: true,
										uniqueness: {scope: :body}
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
    validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ActiveRecord::Base

	mount_uploader :image, ImageUploader

	belongs_to :category
	belongs_to :user

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user
	has_many :votes, dependent: :destroy
	has_many :voting_users, through: :votes, source: :user

	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings

	has_many :favourites, dependent: :destroy
	has_many :favouriting_users, through: :favourites, source: :user

	has_many :collaborations, dependent: :destroy
	has_many :collaborating_users, through: :collaborations, source: :user

	validates :title, presence: {message: "Post must have a title!"}, uniqueness: true

	validates :body, presence: {message: "Post must have a body!"}

	scope :recent_three, lambda { order("updated_at DESC").limit(3) }


	def liked_by?(user)
		likes.where(user: user).present?
	end

	def like_for(user)
		likes.find_by_user_id(user)
	end

	def favourited_by?(user)
		favourites.where(user: user).present?
	end

	def favourite_for(user)
		favourites.find_by_user_id(user)
	end

	def vote_for(user)
    votes.find_by_user_id(user)
  end

	def vote_result
   count = 0
   votes.each {|v| v.is_up? ? count += 1 : count -= 1 }
   count
 end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :posts, through: :taggings
  has_many :taggings, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag

  validates :tag_id, uniqueness: {scope: :post_id}
end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :avatar, ImageUploader

	has_secure_password

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :liked_posts, through: :likes, source: :post
	has_many :votes, dependent: :destroy
	has_many :voted_posts, through: :votes, source: :post
	has_many :collaborations, dependent: :destroy
	has_many :collaborated_posts, through: :collaborations, source: :post

	has_many :taggings, dependent: :destroy
	has_many :tagged_posts, through: :taggings, source: :post

	has_many :favourites, dependent: :destroy
	has_many :favourited_posts, through: :favourites, source: :post

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true,
						format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	def full_name
		"#{first_name} #{last_name}".strip.squeeze(" ")
	end

	def recent_five_made
		posts.order("updated_at DESC").limit(5)
	end

	def recent_five_joins
		collaborated_posts.order("created_at DESC").limit(5)
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:edit, :update, :destroy, :show]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :authorize, only: [:edit]

	def index
		@posts = Post.page(params[:page]).per(8).order("id ASC")
	end

	def new
		@post = Post.new(title: "Enter a title!", body: "What's there to say?")
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user

		if @post.save
			redirect_to post_path(@post), notice: "Post Created!"
		else
			render :new
		end
	end

	def show
		@comment = Comment.new
		@like = @post.like_for(current_user)
		@vote = @post.vote_for(current_user)
		@favourite = @post.favourite_for(current_user)
		@collaboration = @post.collaborating_users
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to post_path(@post), notice: "Post has been updated"
		else
			render :edit
		end
	end

	def destroy
		authorize_delete
		@post.destroy
		redirect_to posts_path, notice: "Post Deleted"
	end

private

	def post_params
		post_params = params.require(:post).permit([:title, :body, :category_id, {tag_ids: []}, :image])
	end

	def find_post
		@post = Post.find params[:id]
	end

	def authorize
    redirect_to root_path, alert: "Access denied." unless can? :edit, @post
  end

	def authorize_delete
		redirect_to post_path(@post), alert: "Access denied" unless can? :destroy, @post
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
			sdf
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/posts/_buttons.html.erb
	<% if @post.liked_by?(current_user) %>
		<div class="button-select">
			<%= button_to "☹", post_like_path(@post, @like), method:  :delete,  :class => 'button likes' %>
		</div>
	<% else %>
		<div class="button-select">
			<%= button_to "♥︎", post_likes_path(@post), method:   :post, :class   => 'button likes' %>
		</div>
	<% end %>

	<% if @post.favourited_by?(current_user)%>
  	<div class="button-select">
			<%= button_to "★", post_favourite_path(@post,@favourite), method: :delete, :class =>'button fave'  %>
		</div>
  <% else %>
    <div class="button-select">
			<%= button_to "☆", post_favourites_path(@post), method: :post, :class =>'button fave' %>
    </div>
	<% end %>

	<% if @vote.nil? %>
		<div class="button-select">
			<%= button_to "⬆︎", post_votes_path(@post, {vote: {is_up: true}}), method: :post, :class => 'button vote' %>
		</div>
		<div class="button-select">
			<%= button_to "⬇︎", post_votes_path(@post, {vote: {is_up: false}}), method: :post, :class => 'button vote' %>
		</div>

	<% elsif @vote.is_up? %>
		<div class="button-select">
			<%= button_to "⬆︎", post_vote_path(@post, @vote), method: :delete, :class => 'button vote-up', :id => 'up' %>
		</div>
		<div class="button-select">
			<%= button_to "⬇︎", post_vote_path(@post, @vote, {vote: {is_up: false}}), method: :patch, :class => 'button vote' %>
		</div>

	<% else %>
		<div class="button-select">
			<%= button_to "⬆︎", post_vote_path(@post, @vote, {vote: {is_up: true}}), method: :patch, :class => 'button vote' %>
		</div>
		<div class="button-select">
			<%= button_to "⬇︎", post_vote_path(@post, @vote), method: :delete, :class => 'button vote-down', :id => 'down' %>
		</div>
	<% end %>

	<% if can? :edit, @post  %>
		<div class="button-select">
			<%= button_to "Leave", post_collaboration_path(@post, 	@collaboration), method: :delete, :class => 'button-long join' %>
		</div>

	<% else %>
		<div class="button-select">
			<%= button_to "Join", post_collaborations_path(@post), method: :post, :class => 'button-long leave' %>
		</div>
	<% end %>

app/views/posts/_collaborators.html.erb
<h4>Collaborator(s):</h4>
<ul>
	<% @post.collaborating_users.each do |user| %>
		<li><%= link_to user.full_name, user_path(user) %></li>
	<% end %>
</ul>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<div class="form-group">
		<%= f.input :title %>
	</div>

	<div class="form-group">
		<%= f.input :body %>
	</div>

	<div class="form-group">
  	<%= f.input :image %>
	</div>

	<div class="form-group">
  	<%= f.label :category %>
  	<%= f.collection_select :category_id, Category.all, :id, :title, html: {class: "form-control"}  %>
  </div>

	<div class="form-group">
  	<%#= f.label :tag_ids %>
  	<%#= f.collection_check_boxes :tag_ids, Tag.all, :id, :name  %>
  </div>

	<div class="form-group">
  	<%= f.label "Collaborators" %>
	</div>
	<div class="check-boxes">
  	<% users = @post.persisted? ? User.where(["id != ?",@post.user.id]) : User.where(["id != ?", current_user.id]) %>
  	<%= f.collection_check_boxes :collaborating_user_ids, users, :id,:full_name %>
  </div>

	<div>
  	<%= f.submit "Submit!", :class => "submit-button" %>
	</div>
<% end %>

app/views/posts/_info.html.erb
<% if @post.likes.length == 1 %>
	<%= @post.likes.length %> Like,
<% else %>
	<%= @post.likes.length %> Likes,
<% end %>

Vote Popularity: <%= @post.vote_result %>

app/views/posts/_options.html.erb
<div class="post-options">
	<% if can?(:edit, @post) %>
		<h4>[Post Options]</h4>
		<%= link_to "Edit", edit_post_path(@post) %> ::
	<% end %>

	<% if can?(:destroy, @post) %>
		<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you wanto delete this?"} %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="body" style="margin-left: 200px;">
	<h1>Edit Post: </h1>
	<div class="breaker"></div>
	<%= render "form" %>
</div>

app/views/posts/index.html.erb
<%# Ability to list all the posts in the app
On the listing page there should be a link to visit the post display page

Edit and Delete links %>
<div class="body">
	<h1>Posts Index</h1>

	<% @posts.each do |post| %>

		<h3><%= link_to post.title, post_path(post) %></h3>

		<div id="options">
			<% if can?(:edit, @post) %>

				[Post Options]
				<%= link_to "Edit", edit_post_path(@post) %> ::
			<% end %>

			<% if can?(:destroy, @post) %>
				<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you wanto delete this?"} %>
			<% end %>
		</div>
		<div class="break"></div>
		<% end %>
	<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="body" style="margin-left: 200px;">
	<h1>New Post: </h1>
	<div class="breaker"></div>
	<%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="body">
  <div class="row">
    <div class="col-md-7">

      <h1><%= @post.title %></h1>
      <h4>
        Created on: <%= formatted_date(@post.created_at) %> by <%= @post.user.full_name %>

        <div class="tags">
          Tags:
            <% @post.tag_ids.each do |p| %>
              <%= Tag.find(p).name %>,
            <% end %>
        </div>
      </h4>

      <h5> <%= @post.body %> </h5>

      <%= render "options" %>

      <div class="collaborators">
        <%= render "collaborators" %>
      </div>

      <div class="post-info">
        <%= render "info" %>
      </div>

      <div class="container">
        <div class="button-options">
          <%= render "buttons" %>
        </div>
      </div>

      <div class="post-image">
        <%= image_tag @post.image.url(:resized_image) %>
      </div>

    </div>

    <div class="col-md-5">
      <div class="comment-form">
        <h3>Submit a comment:</h3>
        <%= render "comments/form" %>
      </div>

      <h2>Comments</h2>
      <div id="comments">
        <%= render "comments/comment" %>
      </div>
    </div>

  </div>
</div>